EMAIL_FROM = "informesreinsofia@gmail.com"
EMAIL_TO = "tutors@fundacioesportbalear.es"
EMAIL_PASSWORD = "yxkjkjjkzabnrxsj"

# --- Credenciales de login (usuarios tutores) ---
[auth]
israel = "PampinIsra"
marta = "OliverMarta"
eva = "Milan"